apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvr.fullname" . }}
  labels:
    {{- include "pvr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pvr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "pvr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pvr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: :80
            - name: DEFAULT_URI
              # value: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
              value: {{ include "pvr.fullname" . }}-https://localhost
            # - name: PWA_UPSTREAM
            #   value: {{ include "pvr.fullname" . }}-pwa:3000
            # - name: MERCURE_PUBLISHER_JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ include "pvr.fullname" . }}
            #       key: mercure-jwt-secret
            # - name: MERCURE_SUBSCRIBER_JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ include "pvr.fullname" . }}
            #       key: mercure-jwt-secret
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: database-url
            {{- if or .Values.mongodb.enabled .Values.mongodb.url }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: mongodb-url
            - name: MONGODB_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: mongodb-db
            {{- end }}
            {{- if or .Values.redis.enabled .Values.redis.url }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: redis-url
            {{- end }}
            - name: CADDY_GLOBAL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "pvr.fullname" . }}
                  key: caddy-global-options
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
